### ISSUE TITLE
Wrong spelling of word responsive 

### ISSUE THREAD

**Issue by preeteeg** [konrad-k/formir#6]
<img width="1440" alt="Screen Shot 2020-05-18 at 3 03 22 PM" src="https://user-images.githubusercontent.com/2293014/82206228-e9437b00-9918-11ea-9260-b71cef1bb5c6.png">

Formir is open-source pure CSS Framework
for _**resposive**_ web developing is wrongly spelled.

**Comment by konrad-k** [comment]
Thanks @preeteeg , issue fixed.
